[ignore]
extensions = [
    ".exe",
    ".dll",
    ".so",
    ".dylib",
    ".zip",
    ".tar",
    ".gz",
    ".bz2",
    ".xz",
    ".7z",
    ".rar",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".webp",
    ".svg",
    ".mp4",
    ".mov",
    ".avi",
    ".mkv",
    ".pdf",
    ".woff",
    ".woff2",
    ".ttf",
    ".otf",
    ".class",
    ".o",
    ".a",
    ".db",
    ".sqlite",
    ".bin",
    ".img",
    ".iso"
]

dirs = [
    'node_modules',
    '.git',
    'venv',
    '__pycache__',
    'dist',
    'build',
    '.venv',
    'env',
    '.tox',
    '.idea'
]
